Update snyk_scan.yml

diff --git a/.github/workflows/snyk_scan.yml b/.github/workflows/snyk_scan.yml
--- a/.github/workflows/snyk_scan.yml
+++ b/.github/workflows/snyk_scan.yml
@@ -1,54 +1,47 @@
 name: Example workflow for Node using Snyk
+
 on: push
+
 jobs:
   security:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/node@master
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          command: code test
-          args: --sarif-file-output=snyk.sarif
-      - name: Output SARIF for debugging
-        run: |
-          echo "SARIF results for debugging:"
-          jq '.runs[0].tool.driver.rules[0]' snyk.sarif
-      - name: Print SARIF File
-        run: cat snyk.sarif
-          
-      - name: Calculate and save vulnerability details
-        run: |
-          echo "Parsing Snyk SARIF output..."
-          total_vulnerabilities=$(jq '[.runs[].results[]] | length' snyk.sarif)
-          echo "RESULTS_LENGTH=$total_vulnerabilities" >> $GITHUB_ENV
-          high_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="error")] | length' snyk.sarif)
-          medium_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="warning")] | length' snyk.sarif)
-          low_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="note")] | length' snyk.sarif)
+    - uses: actions/checkout@master
 
-          high_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error") | .shortDescription.text' snyk.sarif | wc -l)
-          medium_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning") | .shortDescription.text' snyk.sarif | wc -l)
-          low_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "note") | .shortDescription.text' snyk.sarif | wc -l)
+    - name: Run Snyk to check for vulnerabilities
+      uses: snyk/actions/node@master
+      continue-on-error: true
+      env:
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      with:
+        command: code test
+        args: --sarif-file-output=snyk.sarif
 
-          readarray -t high_vulnerability_details < <(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error") | [.shortDescription.text | tostring, (if .locations then (.locations[] | .physicalLocation.artifactLocation.uri + ":" + (.physicalLocation.region.startLine | tostring)) else [] end)] | join(", ")' snyk.sarif)
+    - name: Calculate and save vulnerability details
+      run: |
+        echo "Parsing Snyk SARIF output..."
+        total_vulnerabilities=$(jq '.runs[].tool.driver.rules | length' snyk.sarif)
+        echo "RESULTS_LENGTH=$total_vulnerabilities" >> $GITHUB_ENV
 
-          readarray -t medium_vulnerability_details < <(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning") | .shortDescription.text as $description | .locations[] | "Description: \($description), path: \(.physicalLocation.artifactLocation.uri), line: \(.physicalLocation.region.startLine)"' snyk.sarif)
-          
-          readarray -t low_vulnerability_details < <(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "note") | .shortDescription.text | tostring' snyk.sarif)
-          echo "Sending notification to Slack..."
-          curl -X POST -H 'Content-type: application/json' --data '{
-            "text": "Snyk Vulnerability Report:\n\nTotal Vulnerabilities: '"$total_vulnerabilities"'\n\nHigh: '"$high_vulnerabilities"'\n'"$high_vulnerability_details"'\n\nMedium: '"$medium_vulnerabilities"'\n'"$medium_vulnerability_details"'\n\nLow: '"$low_vulnerabilities"'\n'"$low_vulnerability_details"'"
-          }' ${{ secrets.SLACK_WEBHOOK_URL }}
-      
-      - name: Pass or Fail the Job
-        run: |
-              if ["$RESULTS_LENGTH" !=0 ]; then
-                echo "Job Failed"
-                exit 1
-              else
-                echo "Pass"
-              fi
+        high_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error") | .shortDescription.text' snyk.sarif | wc -l)
+        medium_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning") | .shortDescription.text' snyk.sarif | wc -l)
+        low_vulnerabilities=$(jq '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "note") | .shortDescription.text' snyk.sarif | wc -l)
 
+        high_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error") | .shortDescription.text' snyk.sarif | paste -sd "\n" -)
+        medium_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning") | .shortDescription.text' snyk.sarif | paste -sd "\n" -)
+        low_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "note") | .shortDescription.text' snyk.sarif | paste -sd "\n" -)
+
+        echo "Sending notification to Slack..."
+        curl -X POST -H 'Content-type: application/json' --data '{
+          "text": "Snyk Vulnerability Report:\n\nTotal Vulnerabilities: '"$total_vulnerabilities"'\n\nHigh: '"$high_vulnerabilities"'\n'"$high_vulnerability_details"'\n\nMedium: '"$medium_vulnerabilities"'\n'"$medium_vulnerability_details"'\n\nLow: '"$low_vulnerabilities"'\n'"$low_vulnerability_details"'"
+        }' ${{ secrets.SLACK_WEBHOOK_URL }}
+
+    - name: Pass or Fail the Job
+      run: |
+        if [ "$RESULTS_LENGTH" != 0 ]; then
+          echo "Job Failed"
+          exit 1
+        else
+          echo "Pass"
+        fi
