Update snyk_scan.yml

diff --git a/.github/workflows/snyk_scan.yml b/.github/workflows/snyk_scan.yml
--- a/.github/workflows/snyk_scan.yml
+++ b/.github/workflows/snyk_scan.yml
@@ -11,33 +11,39 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
-          command: code test --json > snyk-result.json
-            cat snyk-result.json
-    
-      - name: Format Slack message
-        id: format-slack-message
+          command: code test
+          args: --sarif-file-output=snyk.sarif
+      - name: Output SARIF for debugging
         run: |
-        vulnerabilities=$(jq -r '.vulnerabilities[] | "* \(.severity) - \(.title)\n  Path: \(.from[] | join(", "))\n  Info: \(.url)"' snyk-result.json)
-        echo "$vulnerabilities" > vulnerabilities.txt
-        summary=$(jq -r '"* \(.uniqueCount) unique vulnerabilities found\n* High: \(.highCount)\n* Medium: \(.mediumCount)\n* Low: \(.lowCount)"' snyk-result.json)
-        echo "$summary" > summary.txt
+          echo "SARIF results for debugging:"
+          jq '.runs[0].tool.driver.rules[0]' snyk.sarif
+      - name: Print SARIF File
+        run: cat snyk.sarif
+          
+      - name: Calculate and save vulnerability details
+        run: |
+          echo "Parsing Snyk SARIF output..."
+          total_vulnerabilities=$(jq '[.runs[].results[]] | length' snyk.sarif)
+          echo "RESULTS_LENGTH=$total_vulnerabilities" >> $GITHUB_ENV
+          high_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="error")] | length' snyk.sarif)
+          medium_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="warning")] | length' snyk.sarif)
+          low_vulnerabilities=$(jq '[.runs[].results[] | select(.level=="note")] | length' snyk.sarif)
 
-      - name: Send Slack notification
-        env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          high_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "error") | [.shortDescription.text, (if .locations then (.locations[] | .physicalLocation.artifactLocation.uri + ":" + (.physicalLocation.region.startLine | tostring)) else [] end)] | join(", ")' snyk.sarif)
+          medium_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning") | .shortDescription.text as $description | .locations[] | "Description: \($description), path: \(.physicalLocation.artifactLocation.uri), line: \(.physicalLocation.region.startLine)" ' snyk.sarif)
+          low_vulnerability_details=$(jq -r '.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "note") | .shortDescription.text' snyk.sarif)
+          
+          echo "Sending notification to Slack..."
+          curl -X POST -H 'Content-type: application/json' --data '{
+            "text": "Snyk Vulnerability Report:\n\nTotal Vulnerabilities: '"$total_vulnerabilities"'\n\nHigh: '"$high_vulnerabilities"'\n'"$high_vulnerability_details"'\n\nMedium: '"$medium_vulnerabilities"'\n'"$medium_vulnerability_details"'\n\nLow: '"$low_vulnerabilities"'\n'"$low_vulnerability_details"'"
+          }' ${{ secrets.SLACK_WEBHOOK_URL }}
+      
+      - name: Pass or Fail the Job
         run: |
-        payload=$(jq -n --arg summary "$(cat summary.txt)" --arg vulnerabilities "$(cat vulnerabilities.txt)" \
-        '{
-          "text": "Snyk Vulnerability Report",
-          "blocks": [
-            {
-              "type": "section",
-              "text": {
-                "type": "mrkdwn",
-                "text": "*Snyk Vulnerability Report*\n\n*Summary:*\n\($summary)\n\n*Details:*\n\($vulnerabilities)"
-              }
-            }
-          ]
-        }')
-        echo "$payload" > payload.json
-        curl -X POST -H 'Content-type: application/json' --data "@payload.json" $SLACK_WEBHOOK_URL
+              if ["$RESULTS_LENGTH" !=0 ]; then
+                echo "Job Failed"
+                exit 1
+              else
+                echo "Pass"
+              fi
+
